# Site settings
title: LF Blog    				 
SEOTitle: 林峯的博客 | LF Blog    	 
header-img: img/post-bg-rwd.jpg  
email: linfengchenlinfengchen929@gmail.com	
description: "LF Blog"  			 
keyword: "LF, LF Blog, 林峯的博客, chenlinfeng, 陈林峯, iOS, Apple, iPhone" 
url: "https://linfengchen.github.io"          
baseurl: ""     
